spring.application.name=trendsense-market-ai

spring.datasource.url=jdbc:postgresql://localhost:5433/trendsense_market_ai
spring.datasource.username=trendsense_user
spring.datasource.password=trendsense_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true